#!/bin/csh
#

set DIR = /home/birac/MM_KIT/CHARMM/charmm-gui/

set nt = 12

# Generated by CHARMM-GUI (http://www.charmm-gui.org)

# This folder contains GROMACS formatted CHARMM36 force fields, a pre-optimized PDB structure, and GROMACS inputs.
# All input files were optimized for GROMACS 2019.2 or above, so lower version of GROMACS can cause some errors.
# We adopted the Verlet cut-off scheme for all minimization, equilibration, and production steps because it is 
# faster and more accurate than the group scheme. If you have a trouble with a performance of Verlet scheme while 
# running parallelized simulation, you should check if you are using appropriate command line.
# For MPI parallelizing, we recommand following command:
# mpirun -np $NUM_CPU gmx mdrun -ntomp 1


# Minimization
# In the case that there is a problem during minimization using a single precision of GROMACS, please try to use 
# a double precision of GROMACS only for the minimization step.

# step6.0
if ( ! -f step6.0_minimization.gro ) then
    gmx grompp -f $DIR/step6.0_minimization.mdp -o step6.0_minimization.tpr -c step5_input.gro -r step5_input.gro -p topol.top -maxwarn 2
    gmx mdrun -v -deffnm step6.0_minimization
endif

# Equilibration
set cnt    = 1
set cntmax = 6
while ( ${cnt} <= ${cntmax} )
    @ pcnt = ${cnt} - 1
    if ( ${cnt} == 1 ) then
        if ( ! -f step6.{$cnt}_equilibration.gro ) then
            gmx grompp -f $DIR/step6.{$cnt}_equilibration.mdp -o step6.{$cnt}_equilibration.tpr -c step6.{$pcnt}_minimization.gro -r step5_input.gro -p topol.top -maxwarn 2
            gmx mdrun -v -deffnm step6.{$cnt}_equilibration -pin on -pinoffset 0 -ntomp $nt -ntmpi 1
        else
            echo equilibration $cnt done
        endif
    else
        if ( ! -f step6.{$cnt}_equilibration.gro ) then
            gmx grompp -f $DIR/step6.{$cnt}_equilibration.mdp -o step6.{$cnt}_equilibration.tpr -c step6.{$pcnt}_equilibration.gro -r step5_input.gro -p topol.top -maxwarn 2
            gmx mdrun -v -deffnm step6.{$cnt}_equilibration -pin on -pinoffset 0 -ntomp $nt -ntmpi 1
        else
            echo equilibration $cnt done
        endif
    endif
    @ cnt += 1
end

# Production
set cnt    = 1
set cntmax = 5

while ( ${cnt} <= ${cntmax} )
    /opt/gromacs-2022.3/bin/gmx grompp -f $DIR/step7_production.mdp -o md_${cnt}.tpr -c step6.6_equilibration.gro -p topol.top -n index
    @ cnt += 1
end
